## Context

Starting in 2008, every year Forbes Magazine publishes a list of America's best colleges. When it comes to the question everyone seems to be asking, “Is college worth it? this published list of colleges comes handy to take a decision based on student's requirement or desire.

The mission of the college ranking by Forbes Magazine is to conduct an annual review of the undergraduate institutions that deliver the top academics, best experiences, career success and lowest debt. Whether a school is in the Top 10 or near the bottom of the list, the 650 colleges are the best in the country.

For most families, choosing a four-year college is one of the biggest and most expensive decisions they can make. For students, this time of their life may layout their future plans. So choose carefully.

## About Data

The data set contains the rankings of 650 Unites States colleges along with various other statistics pertaining to each school.

<img src ="https://i.ibb.co/sKwQjfw/Stanford.jpg" width=80% height =40%></img>

### Load required packages

In [2]:
import numpy as np 
import pandas as pd

### Load the data into pandas dataframe and view the details

In [3]:
df=pd.read_csv('ForbesAmericasTopColleges2019.csv')
df

,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,SAT Lower,SAT Upper,ACT Lower,ACT Upper,Website
0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,1460.0,1590.0,32.0,35.0,www.harvard.edu
1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,1390.0,1540.0,32.0,35.0,www.stanford.edu
2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,1460.0,1580.0,32.0,35.0,www.yale.edu
3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,1490.0,1570.0,33.0,35.0,web.mit.edu
4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,1430.0,1570.0,31.0,35.0,www.princeton.edu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645,646,New Mexico State University,Las Cruces,NM,Public,13379,14432,8625.0,9582.0,34720,96700.0,64.0,910.0,1160.0,18.0,23.0,www.nmsu.edu
646,647,Indiana State University,Terre Haute,IN,Public,13626,13763,13012.0,9297.0,32938,85600.0,85.0,900.0,1110.0,17.0,23.0,www.indstate.edu
647,648,Emory &amp; Henry College,Emory,VA,Private,1094,1226,19340.0,27155.0,48100,70700.0,72.0,988.0,1170.0,19.0,25.0,www.ehc.edu
648,649,Wells College,Aurora,NY,Private,488,516,22828.0,30207.0,55180,NaN,80.0,NaN,NaN,NaN,NaN,www.wells.edu
649,650,Catawba College,Salisbury,NC,Private,1336,1463,19807.0,23662.0,44921,78100.0,42.0,930.0,1100.0,18.0,23.0,www.catawba.edu

### Dimension of the data

*'shape'* is a property associated with DataFrame. It returns a tuple representing the dimensionality of the DataFrame. First value is giving number of rows and second value is giving number of columns.

In [4]:
df.shape

(650, 17)

### Datatype of the fields in the data

'info()' method prints information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rank                      650 non-null    int64
 1   Name                      650 non-null    object
 2   City                      650 non-null    object
 3   State                     650 non-null    object
 4   Public/Private            650 non-null    object
 5   Undergraduate Population  650 non-null    int64
 6   Student Population        650 non-null    int64
 7   Net Price                 648 non-null    float64
 8   Average Grant Aid         646 non-null    float64
 9   Total Annual Cost         650 non-null    int64
 10  Alumni Salary             635 non-null    float64
 11  Acceptance Rate           648 non-null    float64
 12  SAT Lower                 551 non-null    float64
 13  SAT Upper                 551 non-null    float64
 14  ACT Lower                 553 non-null    float64
 15  ACT Upper                 553 non-null    float64
 16  Website                   645 non-null    object
dtypes: float64(8), int64(4), object(5)
memory usage: 86.5+ KB

### Check the missing values in the data
'isnull()' method detects missing values. It returns a boolean same-sized object indicating if the values are NA. NA values, gets mapped to True values.Everything else gets mapped to False values.

'sum()' method followed by 'isnull()' adds up all the True instances per column to give a summary of missing values per column

In [11]:
df.isnull().sum()

Rank                         0
Name                         0
City                         0
State                        0
Public/Private               0
Undergraduate Population     0
Student Population           0
Net Price                    2
Average Grant Aid            4
Total Annual Cost            0
Alumni Salary               15
Acceptance Rate              2
SAT Lower                   99
SAT Upper                   99
ACT Lower                   97
ACT Upper                   97
Website                      5
dtype: int64

### Data Cleanup

Let's first drop all columns that are not need. 

'drop()' method with 'axis=1' indicates that columns have to be dropped. List of column names to be dropped is passed to the method. 'inplace = True' ensures that the columns are dropped from the DataFrame permanently

In [7]:
df.drop(['Website', 'SAT Lower','SAT Upper','ACT Lower','ACT Upper'], axis=1, inplace=True)

'dropna()' method drops all rows with NA values (by default axis = 0)

In [11]:
df.shape

(628, 12)

In [10]:
df.dropna(inplace=True)

### Reset the index of the dataframe

'reset_index()' resets the index of the DataFrame

'drop' as True, will not try to insert index into DataFrame columns

'inplace' as True resets the index permanently

In [15]:
df.reset_index(inplace=True)
df

,level_0,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate
0,0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0
1,1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0
2,2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0
3,3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0
4,4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,623,644,645,Morehouse College,Atlanta,GA,Private,2202,2219,34928.0,17318.0,48723,98700.0,74.0
624,624,645,646,New Mexico State University,Las Cruces,NM,Public,13379,14432,8625.0,9582.0,34720,96700.0,64.0
625,625,646,647,Indiana State University,Terre Haute,IN,Public,13626,13763,13012.0,9297.0,32938,85600.0,85.0
626,626,647,648,Emory &amp; Henry College,Emory,VA,Private,1094,1226,19340.0,27155.0,48100,70700.0,72.0
627,627,649,650,Catawba College,Salisbury,NC,Private,1336,1463,19807.0,23662.0,44921,78100.0,42.0

### Check the first 5 rows of the dataset
'head()' function is used to view the top records. By default it displays 5 rows.

In [17]:
df.head(10)

,level_0,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate
0,0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0
1,1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0
2,2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0
3,3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0
4,4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0
5,5,5,6,University of Pennsylvania,Philadelphia,PA,Private,13437,25367,24242.0,44801.0,71715,133900.0,9.0
6,6,6,7,Brown University,Providence,RI,Private,7390,10095,30205.0,42455.0,71050,127600.0,8.0
7,7,7,8,California Institute of Technology,Pasadena,CA,Private,1002,2238,24245.0,41408.0,68901,151600.0,8.0
8,8,8,9,Duke University,Durham,NC,Private,7184,16130,35737.0,47836.0,71764,132100.0,10.0
9,9,9,10,Dartmouth College,Hanover,NH,Private,4693,6509,30421.0,47171.0,71827,130900.0,10.0

### Display the last five rows of the dataset
'tail()' function is used to view the last records. By default it displays 5 rows.

In [18]:
df.tail()

,level_0,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate
623,623,644,645,Morehouse College,Atlanta,GA,Private,2202,2219,34928.0,17318.0,48723,98700.0,74.0
624,624,645,646,New Mexico State University,Las Cruces,NM,Public,13379,14432,8625.0,9582.0,34720,96700.0,64.0
625,625,646,647,Indiana State University,Terre Haute,IN,Public,13626,13763,13012.0,9297.0,32938,85600.0,85.0
626,626,647,648,Emory &amp; Henry College,Emory,VA,Private,1094,1226,19340.0,27155.0,48100,70700.0,72.0
627,627,649,650,Catawba College,Salisbury,NC,Private,1336,1463,19807.0,23662.0,44921,78100.0,42.0

### Recheck the dimension and info of the data

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628 entries, 0 to 627
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   level_0                   628 non-null    int64
 1   index                     628 non-null    int64
 2   Rank                      628 non-null    int64
 3   Name                      628 non-null    object
 4   City                      628 non-null    object
 5   State                     628 non-null    object
 6   Public/Private            628 non-null    object
 7   Undergraduate Population  628 non-null    int64
 8   Student Population        628 non-null    int64
 9   Net Price                 628 non-null    float64
 10  Average Grant Aid         628 non-null    float64
 11  Total Annual Cost         628 non-null    int64
 12  Alumni Salary             628 non-null    float64
 13  Acceptance Rate           628 non-null    float64
dtypes: float64(4), int64(6), object(4)
memory usage: 68.8+ KB

In [24]:
print('rows:',df.shape[0],'cols:',df.shape[1])

rows: 628 cols: 14

# Data Analysis

### Get Summary of Data

'describe()' method generates descriptive statistics. Descriptive statistics include those that summarize the central
tendency, dispersion and shape of a dataset's distribution, excluding 'NaN' values

In [29]:
df.describe()

,count,mean,std,min,25%,50%,75%,max
level_0,628.0,313.500000,181.432265,0.0,156.75,313.5,470.25,627.0
index,628.0,321.122611,185.360460,0.0,160.75,320.5,478.25,649.0
Rank,628.0,322.122611,185.360460,1.0,161.75,321.5,479.25,650.0
Undergraduate Population,628.0,10235.472930,11228.048723,323.0,2062.75,4825.5,15867.00,65100.0
Student Population,628.0,12312.912420,13246.660229,406.0,2294.50,6538.5,18357.25,75044.0
Net Price,628.0,22481.570064,8099.771637,1298.0,16476.00,22065.0,27880.75,47270.0
Average Grant Aid,628.0,19971.522293,11214.740998,2975.0,9253.00,19605.0,27431.00,50897.0
Total Annual Cost,628.0,50722.579618,12670.126944,8646.0,40076.00,50478.0,60965.00,75735.0
Alumni Salary,628.0,98616.242038,14026.078146,70700.0,88600.00,96300.0,105400.00,158200.0
Acceptance Rate,628.0,61.721338,21.795857,5.0,49.00,67.0,78.00,100.0

### 1) Which are the top 5 colleges listed in the Forbes Magazine 2019?

As we need the 'Name' of the colleges, we first pick the 'Name' column and then display the top 5 rows using head() function

<img src ="https://i.ibb.co/dj0PFhK/Harvard.jpg" width=80% height =40%></img>

In [33]:
top5=df.Name.head()

We can also save the information in an object 'top5' and display it

In [37]:
df[['Name','City','State']].head(5)

                                    Name       City State
0                     Harvard University  Cambridge    MA
1                    Stanford University   Stanford    CA
2                        Yale University  New Haven    CT
3  Massachusetts Institute of Technology  Cambridge    MA
4                   Princeton University  Princeton    NJ

### 2) Which state and city do the top 5 colleges belong to?

As we need the 'Name', 'City' and 'State' of the colleges, we first pick the required columns and then display the top 5 rows using head() function

Note:

As 'City' and 'State' are immediate columns after 'Name', iloc can also be used to get the results

### 3) How many states and which all states have the colleges listed by Forbes?

'nunique()' returns number of unique elements in the object. As we want number of unique states, we first pick up the 'State' column of the DataFrame and then call nunique() function

In [39]:
df.State.nunique()

51

'unique()' function returns unique values of Series object. Hence, we first pick up the 'State' column of the DataFrame and then call unique() function to get all all the States

AttributeError: 'Series' object has no attribute 'value_count'

### 4) In all how many private and public colleges are there in the given list?

'Public/Private' column is of object data type in the DataFrame.

'value_count()' returns a series containing counts of unique values

In [43]:
df[['Public/Private']].value_counts()

Public/Private
Private           384
Public            244
Name: count, dtype: int64

### 5) From the list how many colleges are there within each State? Which State has highest number of colleges?

As we have to find number of colleges within each State, we first group (groupby()) the data based on 'State'. For each State we then count the colleges using number of unique values (nunique())  in 'Name' field.

As we want the 'State' with highest number of colleges, we sort the values (sort_values()) in descending order to get the results.

In [45]:
df.groupby(by='State').Name.nunique().sort_values(ascending = False)

State
NY    64
CA    56
PA    39
MA    31
OH    29
IL    25
TX    25
FL    20
NC    19
IN    18
VA    18
MN    18
MI    16
TN    14
GA    14
NJ    13
WI    13
IA    13
KY    12
MO    12
WA    12
MD    12
CO    11
OR    11
CT     9
SC     8
LA     8
AL     7
RI     7
OK     6
NE     6
ME     5
MS     5
DC     5
AR     4
VT     4
UT     4
MT     4
SD     4
AZ     4
ID     4
NH     3
KS     3
NM     3
NV     2
AK     2
ND     2
HI     1
DE     1
WV     1
WY     1
Name: Name, dtype: int64

### 6) What is percentage of undergraduates in each college? (Add a new field to calculate)

Divsion of 'Undergraduate Population' by 'Student Population' multiplied by 100 will give percentage of undergraduates.

round() method will round off the derived value to 2 decimal places which is then stored in new field 'Percentage UG'

In [59]:
df[['Name','ug']].sort_values(by='ug',ascending=False)

                                       Name     ug
556  University of Texas, Rio Grande Valley  99.99
552                      Oakland University  99.94
246            Saint John's University (MN)  99.94
357                    Salisbury University  99.92
338                     St. Norbert College  99.86
..                                      ...    ...
21                 Johns Hopkins University  31.11
496                      Webster University  29.30
342                         Simmons College  29.05
13                      Columbia University  27.99
471            Nova Southeastern University  23.28

[628 rows x 2 columns]

In [55]:
df

,level_0,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,ug
0,0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,44.49
1,1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,47.92
2,2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,49.97
3,3,3,4,Massachusetts Institute of Technology,Cambridge,MA,Private,4680,11466,20771.0,43248.0,67430,155200.0,7.0,40.82
4,4,4,5,Princeton University,Princeton,NJ,Private,5659,8273,9327.0,48088.0,66150,139400.0,6.0,68.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
623,623,644,645,Morehouse College,Atlanta,GA,Private,2202,2219,34928.0,17318.0,48723,98700.0,74.0,99.23
624,624,645,646,New Mexico State University,Las Cruces,NM,Public,13379,14432,8625.0,9582.0,34720,96700.0,64.0,92.70
625,625,646,647,Indiana State University,Terre Haute,IN,Public,13626,13763,13012.0,9297.0,32938,85600.0,85.0,99.00
626,626,647,648,Emory &amp; Henry College,Emory,VA,Private,1094,1226,19340.0,27155.0,48100,70700.0,72.0,89.23
627,627,649,650,Catawba College,Salisbury,NC,Private,1336,1463,19807.0,23662.0,44921,78100.0,42.0,91.32

### 7) Which are the 5 colleges with highest percentage of undergraduates?

Let's just pick up 'Name' and 'Percentage UG' field, sort by 'Percentage UG' in descending order to get the desired ouput

### 8) 5 colleges that receive highest Average Grant Aid?

Sort 'Average Grant Aid' in descending order and pick up the top 5 colleges using 'Name' field

In [62]:

df.sort_values(by= "Average Grant Aid",ascending=False).head(5)

,level_0,index,Rank,Name,City,State,Public/Private,Undergraduate Population,Student Population,Net Price,Average Grant Aid,Total Annual Cost,Alumni Salary,Acceptance Rate,ug
2,2,2,3,Yale University,New Haven,CT,Private,6483,12974,18627.0,50897.0,71290,138300.0,7.0,49.97
1,1,1,2,Stanford University,Stanford,CA,Private,8402,17534,13261.0,50134.0,69109,145200.0,5.0,47.92
0,0,0,1,Harvard University,Cambridge,MA,Private,13844,31120,14327.0,49870.0,69600,146800.0,5.0,44.49
26,26,27,28,Amherst College,Amherst,MA,Private,1836,1945,22463.0,49467.0,71300,116500.0,13.0,94.40
13,13,13,14,Columbia University,New York,NY,Private,8523,30454,24231.0,49185.0,74199,126800.0,7.0,27.99


### 9) What is the average Undergraduate population in State of 'CA'?

First lets filter the DataFrame and get only rows with 'State' as 'CA'

We then pick up the 'Undergraduate Population' for the above subset and calculate its mean

round off the final value to 2 decimal places using the round() function

In [64]:
round(df[df.State=='CA']['Undergraduate Population'].mean(),2)

np.float64(13186.91)

### 10) Which are the colleges where chances of admission is high?

As per the data dictionary 'Acceptance Rate' field provides information on chances of admission. We can sort this column in descending order to get the results

### 11) Find if there are any 'Art' colleges in the list

To find a specific string value 'Art' we will use the 'contains()' method. We will pass the string in the paranthesis which needs to be located in the dataframe variable.

### 12) Lets divide the Alumni Salary equally into 3 buckets (Low Salary - L; Medium Salary - M; High Salary - H ) and check which colleges falls in 'H' bucket

Take a copy of the original DataFrame to work on

'cut()' function bins values into discrete intervals. 'cut()' function is used when you need to segment and sort data values into bins. This function is also useful for going from a continuous variable to a categorical variable.

In the above code we have created 3 bins using 'Alumni Salary' column. Lowest range of salary is labelled as 'L', middle range is labelled as 'M' and highest range of salary is labelled as 'H'. These labels are saved in a new column 'Alumni Sal Level'.

Note: The entire range of the 'Alumni Salary' has been divided into 3 equal ranges i.e. 3 bins

### 13) Let's check the mean Alumni Salary at each level

### 14) Let's create a new dataframe to further analyze the 28 colleges with High Alumni Salary

Passing 'include = 'all'' to describe() method provides descriptive summary of all fields in the DataFrame. 'T' property transposes the table which helps in reviewing the statistics per column

### Happy Learning!!!